version: '2'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=SS_project
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3320:3306"
  web:
    build: ./webserver
    ports:
      - "8080:2015"
    volumes:
      - ./www:/var/www/html
      - ./assets:/var/www/assets
  php:
    build: ./php
    volumes:
      - ./www:/var/www/html
      - ./assets:/var/www/assets
    environment:
      - ASSETS_PATH=/var/www/assets
    depends_on:
      - db
  nodejs:
    build: ./nodejs
    volumes:
      - ./:/app
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"