version: '2'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=SS_project
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3320:3306"
  php:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
  nodejs:
    build: ./nodejs
    volumes:
      - ./:/app
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"